// <auto-generated />
using System;
using Api1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("Api1.Models.Dzivoklis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Dzivojama_Platiba")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Iedzivotaju_Skaits")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Istabu_Skaits")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MajaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Maja_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Numurs")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Pilna_Platiba")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Stavs")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MajaId");

                    b.ToTable("Dzivokli");
                });

            modelBuilder.Entity("Api1.Models.Iedzivotaja_Dzivoklis", b =>
                {
                    b.Property<int>("Iedzivotajs_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dzivoklis_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Is_Owner")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Saikne_Ar_Dzivokli")
                        .HasColumnType("TEXT");

                    b.HasKey("Iedzivotajs_Id", "Dzivoklis_Id");

                    b.HasIndex("Dzivoklis_Id");

                    b.ToTable("Iedzivotaju_Dzivokli");
                });

            modelBuilder.Entity("Api1.Models.Iedzivotajs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("Dzimsanas_Datums")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DzivoklisId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dzivoklis_Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("E_Mail")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Is_Owner")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Personas_Kods")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Saikne_Ar_Dzivokli")
                        .HasColumnType("TEXT");

                    b.Property<long?>("Telefons")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uzvards")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vards")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DzivoklisId");

                    b.ToTable("Iedzivotaji");
                });

            modelBuilder.Entity("Api1.Models.Maja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Iela")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Numurs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pasta_Indekss")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pilseta")
                        .HasColumnType("TEXT");

                    b.Property<string>("Valsts")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Majas");
                });

            modelBuilder.Entity("Api1.Models.Majas_Dzivoklis", b =>
                {
                    b.Property<int>("Maja_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dzivoklis_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Maja_Id", "Dzivoklis_Id");

                    b.HasIndex("Dzivoklis_Id");

                    b.ToTable("Majas_Dzivokli");
                });

            modelBuilder.Entity("Api1.Models.Dzivoklis", b =>
                {
                    b.HasOne("Api1.Models.Maja", "Maja")
                        .WithMany("Dzivokli")
                        .HasForeignKey("MajaId");

                    b.Navigation("Maja");
                });

            modelBuilder.Entity("Api1.Models.Iedzivotaja_Dzivoklis", b =>
                {
                    b.HasOne("Api1.Models.Dzivoklis", "Dzivoklis")
                        .WithMany("Iedzivotaja_Dzivokli")
                        .HasForeignKey("Dzivoklis_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api1.Models.Iedzivotajs", "Iedzivotajs")
                        .WithMany("Iedzivotaja_Dzivokli")
                        .HasForeignKey("Iedzivotajs_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dzivoklis");

                    b.Navigation("Iedzivotajs");
                });

            modelBuilder.Entity("Api1.Models.Iedzivotajs", b =>
                {
                    b.HasOne("Api1.Models.Dzivoklis", null)
                        .WithMany("Iedzivotaji")
                        .HasForeignKey("DzivoklisId");
                });

            modelBuilder.Entity("Api1.Models.Majas_Dzivoklis", b =>
                {
                    b.HasOne("Api1.Models.Dzivoklis", "Dzivoklis")
                        .WithMany("Majas_Dzivokli")
                        .HasForeignKey("Dzivoklis_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api1.Models.Maja", "Maja")
                        .WithMany("Majas_Dzivokli")
                        .HasForeignKey("Maja_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dzivoklis");

                    b.Navigation("Maja");
                });

            modelBuilder.Entity("Api1.Models.Dzivoklis", b =>
                {
                    b.Navigation("Iedzivotaja_Dzivokli");

                    b.Navigation("Iedzivotaji");

                    b.Navigation("Majas_Dzivokli");
                });

            modelBuilder.Entity("Api1.Models.Iedzivotajs", b =>
                {
                    b.Navigation("Iedzivotaja_Dzivokli");
                });

            modelBuilder.Entity("Api1.Models.Maja", b =>
                {
                    b.Navigation("Dzivokli");

                    b.Navigation("Majas_Dzivokli");
                });
#pragma warning restore 612, 618
        }
    }
}
